---
title: "Capstone Project - Jigsaw/Analytics Edge - Customer 3"
output:
  html_notebook: default
  pdf_document: default
---


```{r}
rm(list = ls())

#Loading the required packages
library(readxl)
library(dplyr)
library(ggplot2)

library(lubridate)
library(data.table)
library(caTools)
library(caret)
library(car)
```

```{r, message=FALSE, warning=FALSE}
#Load the datasets
data3 = read_excel("Project_Dataset.xlsx", sheet = "Customer3")
```

Customer3: EDA and Data preparation
```{r}
summary(data3)
```


```{r}
str(data3)
```


```{r}
#Converting numeric variables to factor variables
data3$ProdRptCat <- as.factor(data3$ProdRptCat)
data3$PRODSTYLE <- as.factor(data3$PRODSTYLE)
data3$PartNumber <- as.factor(data3$PartNumber)
data3$StoreNumber <- as.factor(data3$StoreNumber)
data3$StateTerritory <- as.factor(data3$StateTerritory)

length(unique(data3$PRODSTYLE))
length(unique(data3$EndDate))
length(unique(data3$StoreNumber))
length(unique(data3$StateTerritory))

#Customer3 sells 10 different types of products and has 70 weeks of transaction data across 1981 stores spread across 55 states 
```


```{r}
#What are the different types of Brands sold in Customer3?
table(data3$PRODSTYLE)

ggplot(data3, aes(x=PRODSTYLE, fill = PRODSTYLE))+
  geom_bar()+
  theme_classic()+
  labs(title = "Product Classification")
#There are 7 products in total, but products 'SP001', 'SP018', 'SPC15' have very less records in the dataset
#There are some empty observations in PRODSTYLE which are shown as NA in the graph
```

```{r}
#Removing observations with null values in PROSTYLE
data3 <- data3 %>%filter(!is.na(PRODSTYLE))
```

```{r}
#How many units of each products sold?
data3 %>% group_by(PRODSTYLE) %>% summarise(sum(UnitsSold))


ggplot(data3, aes(x=PRODSTYLE, y = UnitsSold, color = PRODSTYLE))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "Units Sold", title = "Product Vs Unit Sold")
#The average units sold across each products are in the range of 1. We can see outliers/spike in units sold for certain products, which might be due to heavy advertising/promotion during certain weeks.
#Negative values might be due to product returns
```

```{r}
#How is the revenue(Amount Sold) distributed across products?
ggplot(data3, aes(x=PRODSTYLE, y = AmtSold, color = PRODSTYLE))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "Amount Sold", title = "Product Vs Amount Sold")

#Negative values are seen in most of the products. This might be due to product returns/cashbacks/discounts.
```

```{r}
#We will remove the following 3 products as they have relatively very less observations in the dataset: SP001, SP018, SPC15
data3 <- data3[!data3$PRODSTYLE %in% c("SP001", "SP018", "SPC15"),]
table(data3$PRODSTYLE)

```

```{r}
#Relationship between price and quantity sold across each products?
ggplot(data3, aes(x=AmtSold, y = UnitsSold, col = PRODSTYLE))+
  geom_point()+
  facet_wrap(~PRODSTYLE, ncol = 3)+
  theme_bw()+
  labs(x = "Amount", y = "Units", title = "Quantity Vs Amount Sold")
```

```{r}
#To determine elasticity, we need the unit price of the products sold
data3$UnitPrice <- round((data3$AmtSold/data3$UnitsSold),2)
```

```{r}
#Identify the transactions which has Unit Price <= 0 and Unitssold <= 0
data3 %>% filter(UnitsSold <=0 | UnitPrice <= 0)
#There are 1007 observations in total with negative values
```

```{r}
#Deleting observations with negative values in UnitsSold & UnitPrice.
data3 <- data3 %>% filter(!(UnitsSold <=0 | UnitPrice <= 0))
```

```{r}
#Aggregate dataset based on EndDate and PRODSTYLE
d3 <- data3 %>% group_by(EndDate,PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))
d3$Week <- lubridate::week(ymd(d3$EndDate))
```


```{r}
#Visualizing Price change over the weeks for all products
ggplot(d3, aes(x = EndDate, y = UnitPrice))+
  geom_line(aes(color = PRODSTYLE), size = 1)+
  theme_bw()+
  labs(x="Week Duration", y = "Unit Price", title = "Change in Product prices over Time")

#The price of WD009 has declined over the time and looks like its distribution to Customer 3 has stopped from Jan 2016
#WD017 was introducted to Customer 3 from Sept 2015, and there was a heavy promotion/price decline during Dec 2015
```

```{r}
#Facet Wrapping Price change over the weeks for all products
ggplot(d3, aes(x = EndDate, y = UnitPrice, col=PRODSTYLE))+
  geom_line(size = 1)+
  theme_bw()+
  facet_wrap(~PRODSTYLE, ncol = 2)+
  labs(x="Week Duration", y = "Unit Price", title = "Facet Wrap of Product price change over Time")
```

```{r}
#Visualizing change in quantity sold over the weeks for all products
ggplot(d3, aes(x = EndDate, y = UnitsSold))+
  geom_line(aes(color = PRODSTYLE), size = 1)+
  theme_bw()+
  labs(x="Week Duration", y = "Quantity Sold", title = "Change in Quantity Sold over Time")

#The peak in quantity sold of WD products might be due to promotions. 
#The demand for WD009 products has gradually declined and dropped to 0 after Sept 2015
#WD017 has responded to price decline in Dec 2015, but the product has not picked up demand after returning back to its original price.
```

```{r}
#Visualizing Quantity sold with variation in price for all products
ggplot(d3, aes(x = UnitPrice, y = UnitsSold))+
  geom_point(aes(color = PRODSTYLE))+
  theme_bw()+
  labs(title = "Change in Units Sold with change in Price")

#For WD products, the quantity decreases with increase in Price. On the other hand, for SP products, quantity increases with price increase
```

```{r, message=FALSE, warning=FALSE}
#Splitting Customer1 based on the type of products
d3w1 <- d3 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
d3w1_a <- d3w1[,1]
d3w1 <- d3w1[-1] #Removing EndDate
d3w1$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

d3w2 <- d3 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
d3w2 <- d3w2[-1] #Removing EndDate
d3w2$ModWeek <- seq(1:69) #Adding temporary week to standardize the data


dummy1 <- d3 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- d3 %>% filter(PRODSTYLE == "WD017")
d3w3 <- rbind(dummy1, dummy2)
#We do not have enough history about WD017 which was introduced to replace WD009. So we superimpose historical sales data of WD009 on WD017
d3w3_a <- d3w3[,1]
d3w3 <- d3w3[,-c(1,2)] #Removing EndDate
setnames(d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
d3w3$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

d3s1 <- d3 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
d3s1 <- d3s1[-1] #Removing EndDate
d3s1$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

d3s2 <- d3 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
d3s2 <- d3s2[-1] #Removing EndDate
d3s2$ModWeek <- seq(1:69) #Adding temporary week to standardize the data
```

```{r}
#Merge the product pice and quantity sold based on Weeks
finaldata3 <- full_join(d3w1,d3w2, by = "ModWeek") %>% full_join(.,d3w3, by = "ModWeek") %>% full_join(.,d3s1, by = "ModWeek") %>% full_join(.,d3s2, by = "ModWeek")

finaldata3 <- finaldata3[-c(4,5,10,11,14)]
setnames(finaldata3, old = "Week.x", new = "Week")
finaldata3

```

```{r}
library(corrplot)
M <- cor(finaldata3)
corrplot(M, method = "circle")
```

```{r}
#Creating log transformation
finaldata3$log_WD8_Units <- log(finaldata3$WD8_Units)
finaldata3$log_WD8_Price <- log(finaldata3$WD8_Price)
finaldata3$log_WD12_Units <- log(finaldata3$WD12_Units)
finaldata3$log_WD12_Price <- log(finaldata3$WD12_Price)
finaldata3$log_WD17_Units <- log(finaldata3$WD17_Units)
finaldata3$log_WD17_Price <- log(finaldata3$WD17_Price)
finaldata3$log_SP10_Units <- log(finaldata3$SP10_Units)
finaldata3$log_SP10_Price <- log(finaldata3$SP10_Price)
finaldata3$log_SP11_Units <- log(finaldata3$SP11_Units)
finaldata3$log_SP11_Price <- log(finaldata3$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(99)
split <- sample.split(finaldata3, SplitRatio = 0.85)
train <- subset(finaldata3, split == T)
test <- subset(finaldata3, split == F)
```

```{r}
#WD008
#Linear Regression: Linear-Linear
d3mod1a <- lm(WD8_Units ~ WD8_Price + WD12_Units + WD12_Price + WD17_Units + SP10_Units + SP11_Units, data = train)
summary(d3mod1a)
residualPlot(d3mod1a)
```

```{r}
#Predict Model and evalaute the metrics
predict1 <- predict(d3mod1a, test)
vif(d3mod1a)
RMSE(predict1, test$WD8_Units)
MAE(predict1, test$WD8_Units)
R2(predict1, test$WD8_Units)

```

```{r}
#Linear Regression: Linear-Log
d3mod1b <- lm(WD8_Units ~ log_WD8_Price + log_WD12_Units + log_WD12_Price + log_WD17_Units + log_SP10_Units + log_SP11_Units, data = train)
summary(d3mod1b)
residualPlot(d3mod1b)
```

```{r}
#Predict Model and evalaute the metrics
predict2 <- predict(d3mod1b, test)
vif(d3mod1b)
RMSE(predict2, test$WD8_Units)
MAE(predict2, test$WD8_Units)
R2(predict2, test$WD8_Units)
```

```{r}
#Linear Regression: Log-Linear
d3mod1c <- lm(log_WD8_Units ~ WD8_Price + WD12_Units + WD12_Price + WD17_Units + SP10_Units  + SP11_Units, data = train)
summary(d3mod1c)
residualPlot(d3mod1c)
```

```{r}
#Predict Model and evalaute the metrics
predict3 <- predict(d3mod1c, test)
vif(d3mod1c)
RMSE(predict3, test$log_WD8_Units)
MAE(predict3, test$log_WD8_Units)
R2(predict3, test$log_WD8_Units)
```

```{r}
#Linear Regression: Log-Log
d3mod1d <- lm(log_WD8_Units ~ log_WD8_Price + log_WD12_Units + log_WD12_Price + log_WD17_Units + log_SP10_Units + log_SP11_Units, data = train)
summary(d3mod1d)
residualPlot(d3mod1d)
```

```{r}
#Predict Model and evalaute the metrics
predict4 <- predict(d3mod1d, test)
vif(d3mod1d)
RMSE(predict4, test$log_WD8_Units)
MAE(predict4, test$log_WD8_Units)
R2(predict4, test$log_WD8_Units)
```

```{r}
print("Log-log model gives better accuracy. So lets determine elasticity based on this model")
```


```{r}
#Estimating price elasticity for WD008
e_WD8a <- (-17.010 * (mean(finaldata3$log_WD8_Price) / mean(finaldata3$log_WD8_Units)))
round(e_WD8a,2)
print("A 10% increase in price for WD008 will result in 22.7% decrease in their demand")

#Estimating cross price elasticity for WD008
#Negative sign in the coefficent indicates that WD012 is a complement for WD008
e_WD8b <- (-0.828 * (mean(finaldata3$log_WD12_Price) / mean(finaldata3$log_WD8_Units)))
round(e_WD8b,2)
print("A 10% increase in price for WD012 will result in 1.4% increase in the demand for WD008")

e1 <- c(round(e_WD8a,2), round(e_WD8b,2), NA, NA, NA)
e1
```

```{r}
#WD012
#Linear Regression: Log-Log
d3mod2 <- lm(log_WD12_Units ~ log_WD8_Units + log_WD12_Price +  log_WD17_Price + log_SP10_Price, data = train)
summary(d3mod2)
residualPlot(d3mod2)
```

```{r}
#Predict Model and evalaute the metrics
predict5 <- predict(d3mod2, test)
vif(d3mod2)
RMSE(predict5, test$log_WD12_Units)
MAE(predict5, test$log_WD12_Units)
R2(predict5, test$log_WD12_Units)
```


```{r}
#Estimating price elasticity for WD012
e_WD12b <- (3.694 * (mean(finaldata3$log_WD12_Price) / mean(finaldata3$log_WD12_Units)))
round(e_WD12b,2)
print("A 10% increase in price for WD012 will result in 6.1% increase in their demand")

#Estimating cross price elasticity for WD012
#Negative sign here in the coefficent indicates that WD017 is a subsitute for WD012
e_WD12c <- (-0.182 * (mean(finaldata3$log_WD17_Price) / mean(finaldata3$WD12_Units)))
round(e_WD12c,2)
print("Cross elasticity based on WD012 is zero for WD012 product")

#Postive sign here in the coefficent indicates that SPC10 is a complement for WD012
e_WD12d <- (16.779 * (mean(finaldata3$log_SP10_Price) / mean(finaldata3$WD12_Units)))
round(e_WD12d,2)
print("Cross elasticity based on SPC10 is zero for WD012 product")


e2 <- c( NA, round(e_WD12b,2), round(e_WD12c,2),round(e_WD12d,2), NA)
e2
```


```{r}
#WD017
#Linear Regression: Log-Log
d3mod3 <- lm(log_WD17_Units ~ log_WD8_Price + log_WD8_Units + log_WD17_Price + log_SP10_Units + log_SP11_Price + Week, data = train)
summary(d3mod3)
residualPlot(d3mod3)

```

```{r}
#Predict Model and evalaute the metrics
predict6 <- predict(d3mod3, test)
vif(d3mod3)
RMSE(predict6, test$log_WD17_Units)
MAE(predict6, test$log_WD17_Units)
R2(predict6, test$log_WD17_Units)
```



```{r}
#Estimating price elasticity for WD017
e_WD17c <- (8.633 * (mean(finaldata3$log_WD17_Price) / mean(finaldata3$log_WD17_Units)))
round(e_WD17c,2)
print("A 10% increase in price for WD017 will result in 18.9% increase in their demand")

#Estimating cross price elasticity for WD017
#Negative sign here in the coefficent indicates that WD008 is a subsitute for WD017
e_WD17a <- (-1.431 * (mean(finaldata3$log_WD8_Price) / mean(finaldata3$log_WD17_Units)))
round(e_WD17a,2)
print("A 10% increase in price for WD008 will result in 2.2% decrease in demand for WD017")

#Negative sign here in the coefficent indicates that SPC11 is a subsitute for WD017
e_WD17e <- (-6.469 * (mean(finaldata3$log_SP11_Price) / mean(finaldata3$log_WD17_Units)))
round(e_WD17e,2)
print("A 10% increase in price for WD008 will result in 13.3% decrease in demand for WD017")


e3 <- c(round(e_WD17a,2), NA, round(e_WD17c,2), NA, round(e_WD17e,2))
e3
```


```{r}
#SP10
#Linear Regression: Log-Log
d3mod4 <- lm(log_SP10_Units ~ log_WD8_Units + log_WD17_Units + log_SP10_Price + log_SP11_Units, data = train)
summary(d3mod4)
residualPlot(d3mod4)
```

```{r, message=FALSE, warning=FALSE}
#Predict Model and evalaute the metrics
predict7 <- predict(d3mod4, test)
vif(d3mod4)
RMSE(predict7, test$log_SP10_Units)
MAE(predict7, test$log_SP10_Units)
R2(predict7, test$log_SP10_Units)
```

```{r}
#Estimating price elasticity for SPC10
e_SP10d <- (5.537 * (mean(finaldata3$log_SP10_Price) / mean(finaldata3$log_SP10_Units)))
round(e_SP10d,2)
print("A 10% increase in price for SPC10 will result in 12.6% increase in their demand")


e4 <- c(NA, NA, NA, round(e_SP10d,2), NA)
e4
```


```{r}
#SP11
#Linear Regression: Log-Log
d3mod5 <- lm(log_SP11_Units ~ log_WD8_Units + log_SP10_Units + log_SP11_Price + Week, data = train)
summary(d3mod5)
residualPlot(d3mod5)
```

```{r}
#Predict Model and evalaute the metrics
predict8 <- predict(d3mod5, test)
vif(d3mod5)
RMSE(predict8, test$log_SP11_Units)
MAE(predict8, test$log_SP11_Units)
R2(predict8, test$log_SP11_Units)
```


```{r}
#Estimating price elasticity for SPC11
e_SP11e <- (-14.322 * (mean(finaldata3$log_SP11_Price) / mean(finaldata3$log_SP11_Units)))
round(e_SP11e,2)
print("A 10% increase in price for SPC11 will result in 29.3% decrease in their demand")

e5 <- c(NA, NA, NA, NA, round(e_SP11e,2))
e5
```


```{r}
e_Cust3 <- data.frame(e1,e2,e3,e4,e5)

setnames(e_Cust3, old = c("e1","e2","e3","e4", "e5"), new = c("WD008", "WD012", "WD017", "SPC10", "SPC11"))
rownames(e_Cust3) <- c("WD008", "WD012", "WD017", "SPC10", "SPC11")
e_Cust3

#The diagonals in the matrix represent the price elasticity. The elements in the off-diagonal represent the cross-price elasticity

#SPC11 is the most sensitive(elastic) product to its own price.
#Within WD products, WD008 is the most elastic.
#WD012 is inelastic to the change in its own price.
```



```{r, message=FALSE, warning=FALSE}
#change in price elasticity of WD008 over time?
d3w1_b <- d3w1

d3w1_b$log_WD8_Units <- log(d3w1_b$WD8_Units)
d3w1_b$log_WD8_Price <- log(d3w1_b$WD8_Price)

d3w1_b$Elasticity = 0
for (i in seq(1:69)){
  d3w1_b$Elasticity[i] <- abs(-17.010 * d3w1_b$log_WD8_Price[i]/d3w1_b$log_WD8_Units[i])
}
d3w1_b$EndDate <- d3w1_a$EndDate
```


```{r}
ggplot(d3w1_b, aes(x= EndDate, y = Elasticity))+
  geom_point(color = "blue")+
  geom_line()+
  theme_bw()+
  labs(x="Time Period", title = "WD008 - Change in Elasticity over time")
#Though there is slight decline around May-Sept 2015, The elasticity of WD008 has not drastically changed over the time.
```

```{r}
ggplot(d3w1_b, aes(x = EndDate))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  theme_bw()+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Change in price and quantity sold over Time")
```

```{r, message=FALSE, warning=FALSE}
#change in price elasticity of WD017 over time?
d3w3_b <- d3w3

d3w3_b$log_WD17_Units <- log(d3w3_b$WD17_Units)
d3w3_b$log_WD17_Price <- log(d3w3_b$WD17_Price)

d3w3_b$Elasticity = 0
for (i in seq(1:69)){
  d3w3_b$Elasticity[i] <- abs(8.633 * d3w3_b$log_WD17_Price[i]/d3w3_b$log_WD17_Units[i])
}
d3w3_b$EndDate <- d3w3_a$EndDate
```


```{r}
ggplot(d3w3_b, aes(x= EndDate, y = Elasticity))+
  geom_point(color = "blue")+
  geom_line()+
  theme_bw()+
  labs(x="Time Period", title = "WD017 - Change in Elasticity over time")
#The elasticity of WD017 has remained constant except during Dec 2015. 
```

```{r}
ggplot(d3w3_b, aes(x = EndDate))+
  geom_line(aes(y = WD17_Price), color = "red", size = 1)+
  geom_point(aes(y = WD17_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD17_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  theme_bw()+
  labs(x="Time Period", y = "Unit Price", title = "WD017 - Change in price and quantity sold over Time")
```



```{r}
#Channel/Store Elasticity

#Aggregate the sales of target product WD008 based on StoreNumber
clusterdata3 <- data3

cdata3 <- clusterdata3 %>% filter(PRODSTYLE == "WD008") %>% group_by(StoreNumber) %>% summarise(Tot_UnitsSold = sum(UnitsSold), Avg_UnitPrice = round(mean(UnitPrice),2)) %>% arrange(StoreNumber)

summary(cdata3)
```

```{r}
#Relationship between Avg Unit Price and Total Units Sold
ggplot(cdata3, aes(x = Avg_UnitPrice, y = Tot_UnitsSold))+
  geom_point(col ="red")+
  theme_bw()+
  labs(title = "WD008 Sales - Store Level")
```

```{r}
#Visualize Unit Price based on Store Level
ggplot(cdata3, aes(x = Avg_UnitPrice))+
  geom_histogram(binwidth = 0.1, fill = "red")+
  theme_bw()+
  labs(x = "Unit Price", y = "Count", title = "Unit Price - Store Level")
```


```{r}
#Visualize quantity Sold based on Store Level
ggplot(cdata3, aes(x = Tot_UnitsSold))+
  geom_histogram(binwidth = 10, fill = "red")+
  theme_bw()+
  labs(x = "Quantity sold", y = "Count", title = "Quantity Sold - Store Level")
```


```{r}
#Segmenting Stored based on K-Means clustering

#Standardise the data
z3 <- cdata3[,-1]
cm3 <- apply(z3,2,mean)
sd3 <- apply(z3,2,sd)
z3 <- scale(z3,cm3,sd3)

#Build K-Means with 5 clusters
set.seed(200)
kc3 <- kmeans(z3, 5)
kc3

#Print Scree plot and use elbow method to determine the optimal no of clusters
wss <- 1:15
for (i in 1:15)
{
  wss[i] <- kmeans(z3,i)$tot.withinss
  print(wss[i])
}

number <- 1:15
cdwss3 <- data.frame(wss, number)
ggplot(cdwss3, aes(x = number, y = wss))+
  geom_point(color= "red")+
  geom_line(linetype = 3)+
  theme_bw()+
  scale_x_continuous(breaks = seq(1,15,1))+
  geom_segment(aes(x = 6, y = 250, xend = 6, yend = 1500))+
  geom_text(x = 6.2, y = 1600, label = "Optimal no of clusters = 6")

#Optimal no of cluster is 6. 
#Update the model with new cluster number
kc3 <- kmeans(z3, 6)
kc3

cdata3$Cluster <- kc3$cluster
cdata3$Cluster <- as.factor(cdata3$Cluster)

ggplot(cdata3, aes(x = Avg_UnitPrice, y = Tot_UnitsSold))+ 
  geom_point(aes(color = Cluster))+
  scale_color_brewer(palette = "Set1")+
  theme_bw()
```


```{r}
dummy <- cdata3[,c(1,4)]
clusterdata3 <- left_join(clusterdata3,dummy, by = "StoreNumber") 


#Cluster 1 Analysis
#Aggregate data basedon Cluster 1
cluster1 <- clusterdata3 %>% filter(Cluster == 1) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster1$Week <- lubridate::week(ymd(cluster1$EndDate))
summary(cluster1)
```


```{r, message=FALSE, warning=FALSE}
#Splitting Cluster1 based on the type of products
c1d3w1 <- cluster1 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c1d3w1 <- c1d3w1[-1] #Remvoing EndDate
c1d3w1$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

c1d3w2 <- cluster1 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c1d3w2 <- c1d3w2[-1] #Remvoing EndDate
c1d3w2$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

dummy1 <- cluster1 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster1 %>% filter(PRODSTYLE == "WD017")
c1d3w3 <- rbind(dummy1, dummy2)
c1d3w3 <- c1d3w3[,-c(1,2)] #Remvoing EndDate
setnames(c1d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
c1d3w3$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

c1d3s1 <- cluster1 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c1d3s1 <- c1d3s1[-1] #Remvoing EndDate
c1d3s1$ModWeek <- seq(1:69) #Adding temporary week to standardize the data

c1d3s2 <- cluster1 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c1d3s2 <- c1d3s2[-1] #Remvoing EndDate
c1d3s2$ModWeek <- seq(1:69) #Adding temporary week to standardize the data
```

```{r}
ggplot(c1d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster1")
```



```{r}
#Merge the product pice and quantity sold based on Weeks
cluster1 <- full_join(c1d3w1,c1d3w2, by = "ModWeek") %>% full_join(.,c1d3w3, by = "ModWeek") %>% full_join(.,c1d3s1, by = "ModWeek") %>% full_join(.,c1d3s2, by = "ModWeek")

cluster1 <- cluster1[-c(4,5,10,11,14)]
setnames(cluster1, old = "Week.x", new = "Week")
cluster1

M <- cor(cluster1)
corrplot(M, method = "number")
cluster1 <- cluster1[-c(9,10)]
```

```{r}
#Creating log transformation
cluster1$log_WD8_Units <- log(cluster1$WD8_Units)
cluster1$log_WD8_Price <- log(cluster1$WD8_Price)
cluster1$log_WD12_Units <- log(cluster1$WD12_Units)
cluster1$log_WD12_Price <- log(cluster1$WD12_Price)
cluster1$log_WD17_Units <- log(cluster1$WD17_Units)
cluster1$log_WD17_Price <- log(cluster1$WD17_Price)
cluster1$log_SP10_Units <- log(cluster1$SP10_Units)
cluster1$log_SP11_Price <- log(cluster1$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster1, SplitRatio = 0.85)
train <- subset(cluster1, split == T)
test <- subset(cluster1, split == F)
```

```{r}
d3mod6 <- lm(log_WD8_Units ~ log_WD8_Price + log_WD17_Units + log_SP10_Units + Week, data = train)
summary(d3mod6)
residualPlot(d3mod6)
```

```{r}
#Predict Model and evalaute the metrics
predict6 <- predict(d3mod6, test)
vif(d3mod6)
RMSE(predict6, test$log_WD8_Units)
MAE(predict6, test$log_WD8_Units)
R2(predict6, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in cluster 1
ec1 <- round((-22.924 * (mean(cluster1$log_WD8_Price) / mean(cluster1$log_WD8_Units))),2)
ec1
print("A 10% increase in price for WD008 in Cluster 1 will result in 35.8% decrease in their demand")
```


```{r}
#Cluster 2 Analysis
cluster2 <- clusterdata3 %>% filter(Cluster == 2) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster2$Week <- lubridate::week(ymd(cluster2$EndDate))
summary(cluster2)
```

```{r, message=FALSE, warning=FALSE}
#Splitting Cluster2 based on the type of products
c2d3w1 <- cluster2 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c2d3w1 <- c2d3w1[-1]
c2d3w1$ModWeek <- seq(1:69)

c2d3w2 <- cluster2 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c2d3w2 <- c2d3w2[-1]
c2d3w2$ModWeek <- seq(1:69)

dummy1 <- cluster2 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster2 %>% filter(PRODSTYLE == "WD017")
c2d3w3 <- rbind(dummy1, dummy2)
c2d3w3 <- c2d3w3[,-c(1,2)]
setnames(c2d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
c2d3w3$ModWeek <- seq(1:69)

c2d3s1 <- cluster2 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c2d3s1 <- c2d3s1[-1]
c2d3s1$ModWeek <- seq(1:69)

c2d3s2 <- cluster2 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c2d3s2 <- c2d3s2[-1]
c2d3s2$ModWeek <- seq(1:69)
```

```{r}
ggplot(c2d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster2")
```

```{r}
#Merge the product pice and quantity sold based on Weeks
cluster2 <- full_join(c2d3w1,c2d3w2, by = "ModWeek") %>% full_join(.,c2d3w3, by = "ModWeek") %>% full_join(.,c2d3s1, by = "ModWeek") %>% full_join(.,c2d3s2, by = "ModWeek")

cluster2 <- cluster2[-c(4,5,10,11,14)]
setnames(cluster2, old = "Week.x", new = "Week")
cluster2

M <- cor(cluster2)
corrplot(M, method = "number")
cluster2 <- cluster2[-9]
```

```{r}
#Creating log transformation
cluster2$log_WD8_Units <- log(cluster2$WD8_Units)
cluster2$log_WD8_Price <- log(cluster2$WD8_Price)
cluster2$log_WD12_Units <- log(cluster2$WD12_Units)
cluster2$log_WD12_Price <- log(cluster2$WD12_Price)
cluster2$log_WD17_Units <- log(cluster2$WD17_Units)
cluster2$log_WD17_Price <- log(cluster2$WD17_Price)
cluster2$log_SP10_Units <- log(cluster2$SP10_Units)
cluster2$log_SP11_Units <- log(cluster2$SP11_Units)
cluster2$log_SP11_Price <- log(cluster2$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster2, SplitRatio = 0.85)
train <- subset(cluster2, split == T)
test <- subset(cluster2, split == F)
```

```{r}
d3mod7 <- lm(log_WD8_Units ~ log_WD8_Price + log_WD12_Units + log_WD12_Price + log_WD17_Units + log_SP10_Units + log_SP11_Units, data = train)
summary(d3mod7)
residualPlot(d3mod7)
```

```{r}
#Predict Model and evalaute the metrics
predict7 <- predict(d3mod7, test)
vif(d3mod7)
RMSE(predict7, test$log_WD8_Units)
MAE(predict7, test$log_WD8_Units)
R2(predict7, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in Cluster 2
ec2 <- round((-16.707 * (mean(cluster2$log_WD8_Price) / mean(cluster2$log_WD8_Units))),2)
ec2
print("A 10% increase in price for WD008 in Cluster 2 will result in 26% decrease in their demand")
```



```{r, message=FALSE, warning=FALSE}
#Cluster 3 Analysis
cluster3 <- clusterdata3 %>% filter(Cluster == 3) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster3$Week <- lubridate::week(ymd(cluster3$EndDate))
summary(cluster3)
```

```{r, message=FALSE, warning=FALSE}
#Splitting Cluster3 based on the type of products
c3d3w1 <- cluster3 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c3d3w1 <- c3d3w1[-1]
c3d3w1$ModWeek <- seq(1:69)

c3d3w2 <- cluster3 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c3d3w2 <- c3d3w2[-1]
c3d3w2$ModWeek <- seq(1:69)

dummy1 <- cluster3 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster3 %>% filter(PRODSTYLE == "WD017")
c3d3w3 <- rbind(dummy1, dummy2)
c3d3w3 <- c3d3w3[,-c(1,2)]
setnames(c3d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
#Imputing missing values based on last 4 weeks average
rdummy2 <- data.frame(Week = c(27,28,29,30), WD17_Units = c(68,92,111,125), WD17_Price = c(3.11,4.23,5.32,6.12))
c3d3w3 <- rbind(c3d3w3[1:18,], rdummy2,c3d3w3[19:65,])
c3d3w3$ModWeek <- seq(1:69)

c3d3s1 <- cluster3 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c3d3s1 <- c3d3s1[-1]
c3d3s1$ModWeek <- seq(1:69)

c3d3s2 <- cluster3 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c3d3s2 <- c3d3s2[-1]
c3d3s2$ModWeek <- seq(1:69)
```

```{r}
ggplot(c3d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster3")
```


```{r}
#Merge the product pice and quantity sold based on Weeks
cluster3 <- full_join(c3d3w1,c3d3w2, by = "ModWeek") %>% full_join(.,c3d3w3, by = "ModWeek") %>% full_join(.,c3d3s1, by = "ModWeek") %>% full_join(.,c3d3s2, by = "ModWeek")

cluster3 <- cluster3[-c(4,5,10,11,14)]
setnames(cluster3, old = "Week.x", new = "Week")
cluster3

M <- cor(cluster3)
corrplot(M, method = "number")
cluster3 <- cluster3[-c(8,9,11)]
```

```{r}
#Creating log transformation
cluster3$log_WD8_Units <- log(cluster3$WD8_Units)
cluster3$log_WD8_Price <- log(cluster3$WD8_Price)
cluster3$log_WD12_Units <- log(cluster3$WD12_Units)
cluster3$log_WD12_Price <- log(cluster3$WD12_Price)
cluster3$log_WD17_Units <- log(cluster3$WD17_Units)
cluster3$log_WD17_Price <- log(cluster3$WD17_Price)
cluster3$log_SP11_Units <- log(cluster3$SP11_Units)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster3, SplitRatio = 0.85)
train <- subset(cluster3, split == T)
test <- subset(cluster3, split == F)
```

```{r}
d3mod8 <- lm(log_WD8_Units ~ log_WD8_Price + log_WD12_Units + log_WD12_Price, data = train)
summary(d3mod8)
residualPlot(d3mod8)
```

```{r}
#Predict Model and evalaute the metrics
predict8 <- predict(d3mod8, test)
vif(d3mod8)
RMSE(predict8, test$log_WD8_Units)
MAE(predict8, test$log_WD8_Units)
R2(predict8, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in Cluster 3
ec3 <- round((-8.284 * (mean(cluster2$log_WD8_Price) / mean(cluster2$log_WD8_Units))),2)
ec3
print("A 10% increase in price for WD008 in Cluster 3 will result in 12.9% decrease in their demand")
```



```{r}
#Cluster 4 Analysis
cluster4 <- clusterdata3 %>% filter(Cluster == 4) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster4$Week <- lubridate::week(ymd(cluster4$EndDate))
summary(cluster4)
```

```{r, message=FALSE, warning=FALSE}
#Splitting Cluster4 based on the type of products
c4d3w1 <- cluster4 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c4d3w1 <- c4d3w1[-1]
c4d3w1$ModWeek <- seq(1:69)

c4d3w2 <- cluster4 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c4d3w2 <- c4d3w2[-1]
c4d3w2$ModWeek <- seq(1:69)

dummy1 <- cluster4 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster4 %>% filter(PRODSTYLE == "WD017")
c4d3w3 <- rbind(dummy1, dummy2)
c4d3w3 <- c4d3w3[,-c(1,2)]
setnames(c4d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
c4d3w3$ModWeek <- seq(1:69)

c4d3s1 <- cluster4 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c4d3s1 <- c4d3s1[-1]
c4d3s1$ModWeek <- seq(1:69)

c4d3s2 <- cluster4 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c4d3s2 <- c4d3s2[-1]
c4d3s2$ModWeek <- seq(1:69)
```

```{r}
ggplot(c4d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster4")
```


```{r}
#Merge the product pice and quantity sold based on Weeks
cluster4 <- full_join(c4d3w1,c4d3w2, by = "ModWeek") %>% full_join(.,c4d3w3, by = "ModWeek") %>% full_join(.,c4d3s1, by = "ModWeek") %>% full_join(.,c4d3s2, by = "ModWeek")

cluster4 <- cluster4[-c(4,5,10,11,14)]
setnames(cluster4, old = "Week.x", new = "Week")
cluster4

M <- cor(cluster4)
corrplot(M, method = "number")
cluster4 <- cluster4[-c(4,10,11)]
```

```{r}
#Creating log transformation
cluster4$log_WD8_Units <- log(cluster4$WD8_Units)
cluster4$log_WD8_Price <- log(cluster4$WD8_Price)
cluster4$log_WD12_Price <- log(cluster4$WD12_Price)
cluster4$log_WD17_Units <- log(cluster4$WD17_Units)
cluster4$log_WD17_Price <- log(cluster4$WD17_Price)
cluster4$log_SP10_Units <- log(cluster4$SP10_Units)
cluster4$log_SP10_Price <- log(cluster4$SP10_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster4, SplitRatio = 0.85)
train <- subset(cluster4, split == T)
test <- subset(cluster4, split == F)
```

```{r}
d3mod9 <- lm(log_WD8_Units ~ log_WD17_Units + log_WD17_Price, data = train)
summary(d3mod9)
residualPlot(d3mod9)
```

```{r}
#Predict Model and evalaute the metrics
predict9 <- predict(d3mod9, test)
vif(d3mod9)
RMSE(predict9, test$log_WD8_Units)
MAE(predict9, test$log_WD8_Units)
R2(predict9, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in Cluster 4
ec4 <- NA
#Change in price of WD008 has not affected its change in quantity sold in cluster 4. Hence the elasticity cannot be determined.
```



```{r}
#Cluster 5 Analysis
cluster5 <- clusterdata3 %>% filter(Cluster == 5) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster5$Week <- lubridate::week(ymd(cluster5$EndDate))
summary(cluster5)
```

```{r, message=FALSE, warning=FALSE}
#Splitting Cluster5 based on the type of products
c5d3w1 <- cluster5 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c5d3w1 <- c5d3w1[-1]
c5d3w1$ModWeek <- seq(1:69)

c5d3w2 <- cluster5 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c5d3w2 <- c5d3w2[-1]
c5d3w2$ModWeek <- seq(1:69)

dummy1 <- cluster5 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster5 %>% filter(PRODSTYLE == "WD017")
c5d3w3 <- rbind(dummy1, dummy2)
c5d3w3 <- c5d3w3[,-c(1,2)]
setnames(c5d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
#Imputing missing data based on last 4 weeks of data
rdummy2 <- data.frame(Week = c(26,27,28), WD17_Units = c(24,43,61), WD17_Price = c(3.11,4.23,5.32))
c5d3w3 <- rbind(c5d3w3[1:17,], rdummy2,c5d3w3[18:66,])
c5d3w3$ModWeek <- seq(1:69)

c5d3s1 <- cluster5 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c5d3s1 <- c5d3s1[-1]
c5d3s1$ModWeek <- seq(1:69)

c5d3s2 <- cluster5 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c5d3s2 <- c5d3s2[-1]
c5d3s2$ModWeek <- seq(1:69)
```

```{r}
ggplot(c5d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster5")
```


```{r}
#Merge the product pice and quantity sold based on Weeks
cluster5 <- full_join(c5d3w1,c5d3w2, by = "ModWeek") %>% full_join(.,c5d3w3, by = "ModWeek") %>% full_join(.,c5d3s1, by = "ModWeek") %>% full_join(.,c5d3s2, by = "ModWeek")

cluster5 <- cluster5[-c(4,5,10,11,14)]
setnames(cluster5, old = "Week.x", new = "Week")
cluster5

M <- cor(cluster5)
corrplot(M, method = "number")
cluster4 <- cluster5[-10]

```

```{r}
#Creating log transformation
cluster5$log_WD8_Units <- log(cluster5$WD8_Units)
cluster5$log_WD8_Price <- log(cluster5$WD8_Price)
cluster5$log_WD12_Units <- log(cluster5$WD12_Units)
cluster5$log_WD12_Price <- log(cluster5$WD12_Price)
cluster5$log_WD17_Units <- log(cluster5$WD17_Units)
cluster5$log_WD17_Price <- log(cluster5$WD17_Price)
cluster5$log_SP10_Units <- log(cluster5$SP10_Units)
cluster5$log_SP10_Price <- log(cluster5$SP10_Price)
cluster5$log_SP11_Price <- log(cluster5$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster5, SplitRatio = 0.85)
train <- subset(cluster5, split == T)
test <- subset(cluster5, split == F)
```

```{r}
d3mod10 <- lm(log_WD8_Units ~ log_WD12_Units + log_WD17_Price + log_SP11_Price, data = train)
summary(d3mod10)
residualPlot(d3mod10)
```

```{r}
#Predict Model5 and evalaute the metrics
predict10 <- predict(d3mod10, test)
vif(d3mod10)
RMSE(predict10, test$log_WD8_Units)
MAE(predict10, test$log_WD8_Units)
R2(predict10, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in Cluster 5
ec5 <- NA
#Change in price of WD008 has not affected its change in quantity sold in cluster 5. Hence the elasticity cannot be determined.
```




```{r}
#Cluster 6 Analysis
cluster6 <- clusterdata3 %>% filter(Cluster == 6) %>% group_by(EndDate, PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))

cluster6$Week <- lubridate::week(ymd(cluster6$EndDate))
summary(cluster6)
```

```{r, message=FALSE, warning=FALSE}
#Splitting Cluster5 based on the type of products
c6d3w1 <- cluster6 %>% filter(PRODSTYLE == "WD008") %>% select(Week, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
c6d3w1 <- c6d3w1[-1]
c6d3w1$ModWeek <- seq(1:69)

c6d3w2 <- cluster6 %>% filter(PRODSTYLE == "WD012") %>% select(Week, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
c6d3w2 <- c6d3w2[-1]
c6d3w2$ModWeek <- seq(1:69)

dummy1 <- cluster6 %>% filter(PRODSTYLE == "WD009" & EndDate < "2015-07-18")
dummy2 <- cluster6 %>% filter(PRODSTYLE == "WD017")
c6d3w3 <- rbind(dummy1, dummy2)
c6d3w3 <- c6d3w3[,-c(1,2)]
setnames(c6d3w3, old = c("UnitsSold", "UnitPrice"), new = c("WD17_Units", "WD17_Price"))
c6d3w3$ModWeek <- seq(1:69)

c6d3s1 <- cluster6 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
c6d3s1 <- c6d3s1[-1]
c6d3s1$ModWeek <- seq(1:69)

c6d3s2 <- cluster6 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
c6d3s2 <- c6d3s2[-1]
c6d3s2$ModWeek <- seq(1:69)
```

```{r}
ggplot(c6d3w1, aes(x = Week))+
  geom_line(aes(y = WD8_Price), color = "red", size = 1)+
  theme_bw()+
  geom_point(aes(y = WD8_Units/1000), color = "blue", size = 1)+
  geom_line(aes(y = WD8_Units/1000), color = "steelblue")+
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "Units Sold"))+
  labs(x="Time Period", y = "Unit Price", title = "WD008 - Cluster6")
```


```{r}
#Merge the product pice and quantity sold based on Weeks
cluster6 <- full_join(c6d3w1,c6d3w2, by = "ModWeek") %>% full_join(.,c6d3w3, by = "ModWeek") %>% full_join(.,c6d3s1, by = "ModWeek") %>% full_join(.,c6d3s2, by = "ModWeek")

cluster6 <- cluster6[-c(4,5,10,11,14)]
setnames(cluster6, old = "Week.x", new = "Week")
cluster6

M <- cor(cluster6)
corrplot(M, method = "number")
```

```{r}
#Creating log transformation
cluster6$log_WD8_Units <- log(cluster6$WD8_Units)
cluster6$log_WD8_Price <- log(cluster6$WD8_Price)
cluster6$log_WD12_Units <- log(cluster6$WD12_Units)
cluster6$log_WD12_Price <- log(cluster6$WD12_Price)
cluster6$log_WD17_Units <- log(cluster6$WD17_Units)
cluster6$log_WD17_Price <- log(cluster6$WD17_Price)
cluster6$log_SP10_Units <- log(cluster6$SP10_Units)
cluster6$log_SP11_Units <- log(cluster6$SP11_Units)
cluster6$log_SP10_Price <- log(cluster6$SP10_Price)
cluster6$log_SP11_Price <- log(cluster6$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(101)
split <- sample.split(cluster5, SplitRatio = 0.85)
train <- subset(cluster5, split == T)
test <- subset(cluster5, split == F)
```

```{r}
d3mod11 <- lm(log_WD8_Units ~ log_WD12_Units + log_WD17_Price + log_SP11_Price, data = train)
summary(d3mod11)
residualPlot(d3mod11)
```

```{r}
#Predict Model5 and evalaute the metrics
predict11 <- predict(d3mod11, test)
vif(d3mod11)
RMSE(predict11, test$log_WD8_Units)
MAE(predict11, test$log_WD8_Units)
R2(predict11, test$log_WD8_Units)
```

```{r}
#Estimating price elasticity for WD008 in Cluster 6
ec6 <- NA
#Change in price of WD008 has not affected its change in quantity sold in cluster 6. Hence the elasticity cannot be determined.
```

```{r}
e_Channel3 <- data.frame(ec1,ec2,ec3,ec4,ec5,ec6)

setnames(e_Channel3, old = c("ec1","ec2","ec3","ec4","ec5", "ec6"), new = c("Cluster1", "Cluster2", "Cluster3", "Cluster4", "Cluster5", "Cluster6"))
rownames(e_Channel3) <- "WD008"
e_Channel3

#Cluster 1 stores are the most sensitive(elastic) among all the other segments. 
```


