---
title: "Capstone Project - Jigsaw/Analytics Edge - Customer 2"
output:
  html_notebook: default
  pdf_document: default
---


```{r}
rm(list = ls())

#Loading the required packages
library(readxl)
library(dplyr)
library(ggplot2)

library(lubridate)
library(data.table)
library(caTools)
library(caret)
library(car)
```


```{r, message=FALSE, warning=FALSE}
#Load the dataset
data2 = read_excel("Project_Dataset.xlsx", sheet = "Customer2")
```

Customer1: EDA and Data preparation
```{r}
summary(data2)
```


```{r}
str(data2)
```


```{r}
#Converting numeric variables to factor variables
data2$ProdRptCat <- as.factor(data2$ProdRptCat)
data2$PRODSTYLE <- as.factor(data2$PRODSTYLE)
data2$PartNumber <- as.factor(data2$PartNumber)

length(unique(data2$EndDate))
length(unique(data2$PRODSTYLE))

#Customer2 has 66 weeks of transaction data selling 7 different types of products
```


```{r}
#What are the different types of products sold in Customer2?
table(data2$PRODSTYLE)

ggplot(data2, aes(x=PRODSTYLE, fill = PRODSTYLE))+
  geom_bar()+
  theme_classic()+
  labs(title = "Product Classification")
#There are 7 products in total, but products 'SP001', 'SPC65' and 'WD017' have very less records in the dataset
```


```{r}
#How many units of each products sold?
data2 %>% group_by(PRODSTYLE) %>% summarise(sum(UnitsSold))


ggplot(data2, aes(x=PRODSTYLE, y = UnitsSold, color = PRODSTYLE))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "Units Sold", title = "Product Vs Unit Sold")
#WD008 has the higest average of units sold followed by WD012
```


```{r}
#How is the reveneue(Amount Sold) distributed across products?
ggplot(data2, aes(x=PRODSTYLE, y = AmtSold, color = PRODSTYLE))+
  geom_boxplot()+
  theme_bw()+
  labs(y = "Amount Sold", title = "Product Vs Amount Sold")

#The average revenue of WD008 is around 25000 USD
```


```{r}
#Relationship between price and quantity sold across each products?
ggplot(data2, aes(x=AmtSold, y = UnitsSold, col = PRODSTYLE))+
  geom_point()+
  facet_wrap(~PRODSTYLE, ncol = 4)+
  theme_bw()+
  labs(x = "Amount Sold", y = "Units Sold", title = "Quantity Vs Amount Sold")
```


```{r}
#We will remove the following 3 products as they have relatively very less observations in the dataset: SP001, WDo12, WD017
data2 <- data2[!data2$PRODSTYLE %in% c("SP001", "SPC65", "WD017"),]
summary(data2$PRODSTYLE)
```


```{r, message=FALSE, warning=FALSE}
#To determine elasticity, we need the unit price of the products sold
data2$UnitPrice <- round((data2$AmtSold/data2$UnitsSold),2)
```


```{r}
#Identify the transactions which has Unit Price <= 0 or in UnitPrice <= 0
data2 %>% filter(UnitsSold <=0 | UnitPrice <= 0)
#No negative observations in the dataset
```


```{r, message=FALSE, warning=FALSE}
#Aggregate dataset based on EndDate and PRODSTYLE
d2 <- data2 %>% group_by(EndDate,PRODSTYLE) %>% summarize(UnitsSold = sum(UnitsSold), UnitPrice = round(mean(UnitPrice),2))
d2$Week <- lubridate::week(ymd(d2$EndDate))
d2$ModWeek <- rep(1:66,each = 4)
d2
```


```{r}
#Visualizing Price change over the weeks for all products
ggplot(d2, aes(x = EndDate, y = UnitPrice))+
  geom_line(aes(color = PRODSTYLE), size = 1)+
  theme_bw()+
  labs(x="Week Duration", y = "Unit Price", title = "Change in Product prices over Time")

#Both WD and SP brands are competitively priced over the time.
```

```{r}
#Facet Wrapping Price change over the weeks for all products
ggplot(d2, aes(x = EndDate, y = UnitPrice, col=PRODSTYLE))+
  geom_line(size = 1)+
  theme_bw()+
  facet_wrap(~PRODSTYLE, ncol = 2)+
  labs(x="Week Duration", y = "Unit Price", title = "Facet Wrap of Product price change over Time")
```

```{r}
#Visualizing change in quantity sold over the weeks for all products
ggplot(d2, aes(x = EndDate, y = UnitsSold))+
  geom_line(aes(color = PRODSTYLE), size = 1)+
  theme_bw()+
  labs(x="Week Duration", y = "Quantity Sold", title = "Change in Quantity Sold over Time")

#The peak in quantity sold of WD products might be due to promotions. 
#In Feb 2016, the demand for WD008 has coincided with the price reduction.
```


```{r}
#Visualizing Quantity sold with variation in price for all products
ggplot(d2, aes(x = UnitPrice, y = UnitsSold))+
  geom_point(aes(color = PRODSTYLE))+
  theme_bw()+
  labs(title = "Change in Units Sold with change in Price")

```


```{r, message=FALSE, warning=FALSE}
#Splitting Customer1 based on the type of products
d2w1 <- d2 %>% filter(PRODSTYLE == "WD008") %>% select(Week, ModWeek, WD8_Units = UnitsSold, WD8_Price = UnitPrice)
d2w1 <- d2w1[-1]

d2w2 <- d2 %>% filter(PRODSTYLE == "WD012") %>% select(Week, ModWeek, WD12_Units = UnitsSold, WD12_Price = UnitPrice)
d2w2 <- d2w2[-1]

d2s1 <- d2 %>% filter(PRODSTYLE == "SPC10") %>% select(Week, ModWeek, SP10_Units = UnitsSold, SP10_Price = UnitPrice)
d2s1 <- d2s1[-1]

d2s2 <- d2 %>% filter(PRODSTYLE == "SPC11") %>% select(Week, ModWeek, SP11_Units = UnitsSold, SP11_Price = UnitPrice)
d2s2 <- d2s2[-1]
```

```{r}
#Product WD008 - Price Vs Quantity sold
ggplot(d2w1, aes(x = WD8_Price, y = WD8_Units))+
  geom_point(color = "red")+
  theme_bw()+
  labs(title = "Product WD008 - Price Vs Quantity sold")
#The demand for WD008 product increases as the price decreases
```

```{r}
#Product WD012 - Price Vs Quantity sold
ggplot(d2w2, aes(x = WD12_Price, y = WD12_Units))+
  geom_point(color = "red")+
  theme_bw()+
  labs(title = "Product WD012 - Price Vs Quantity sold")
#The demand for WD012 product increases as the price decreases 
```

```{r}
#Product SPC10 - Price Vs Quantity sold
ggplot(d2s1, aes(x = SP10_Price, y = SP10_Units))+
  geom_point(color = "blue")+
  theme_bw()+
  labs(title = "Product SPC10 - Price Vs Quantity sold")
#There is a random pattern of SPC10 sales 
```


```{r}
#Product SPC11 - Price Vs Quantity sold
ggplot(d2s2, aes(x = SP11_Price, y = SP11_Units))+
  geom_point(color = "blue")+
  theme_bw()+
  labs(title = "Product SPC11 - Price Vs Quantity sold")
#The demand for SPC11 product has increased with decrease in price 
```


```{r}
#Merge the product pice and quantity sold based on Weeks
finaldata2 <- full_join(d2w1,d2w2, by = "ModWeek") %>% full_join(.,d2s1, by = "ModWeek") %>% full_join(.,d2s2, by = "ModWeek")

finaldata2 <- finaldata2[-c(2,5,8,11)]
setnames(finaldata2, old = "Week.x", new = "Week")
finaldata2
```


```{r}
library(corrplot)
M <- cor(finaldata2)
corrplot(M, method = "circle")

```

```{r}
#Creating log transformation
finaldata2$log_WD8_Units <- log(finaldata2$WD8_Units)
finaldata2$log_WD8_Price <- log(finaldata2$WD8_Price)
finaldata2$log_WD12_Units <- log(finaldata2$WD12_Units)
finaldata2$log_WD12_Price <- log(finaldata2$WD12_Price)
finaldata2$log_SP10_Units <- log(finaldata2$SP10_Units)
finaldata2$log_SP10_Price <- log(finaldata2$SP10_Price)
finaldata2$log_SP11_Units <- log(finaldata2$SP11_Units)
finaldata2$log_SP11_Price <- log(finaldata2$SP11_Price)
```

```{r, message=FALSE, warning=FALSE}
#Splitting the dataset into train and test
set.seed(99)
split <- sample.split(finaldata2, SplitRatio = 0.85)
train <- subset(finaldata2, split == T)
test <- subset(finaldata2, split == F)
```

```{r}
#WD008
#Linear Regression: Linear-Linear
d2mod1a <- lm(WD8_Units ~ WD8_Price, data = train)
summary(d2mod1a)
residualPlot(d2mod1a)
```

```{r}
#Predict Model1a and evalaute the metrics
predict1 <- predict(d2mod1a, test)
RMSE(predict1, test$WD8_Units)
MAE(predict1, test$WD8_Units)
R2(predict1, test$WD8_Units)
```

```{r}
#Linear Regression: Linear-Log
d2mod1b <- lm(WD8_Units ~ log_WD8_Price, data = train)
summary(d2mod1b)
residualPlot(d2mod1b)
```

```{r}
#Predict Model1b and evalaute the metrics
predict2 <- predict(d2mod1b, test)
RMSE(predict2, test$WD8_Units)
MAE(predict2, test$WD8_Units)
R2(predict2, test$WD8_Units)
```

```{r}
#Linear Regression: Log-Linear
d2mod1c <- lm(log_WD8_Units ~ WD8_Price + WD12_Price + SP10_Price + Week, data = train)
summary(d2mod1c)
residualPlot(d2mod1c)
```

```{r}
#Predict Model1c and evalaute the metrics
predict3 <- predict(d2mod1c, test)
vif(d2mod1c)
RMSE(predict3, test$log_WD8_Units)
MAE(predict3, test$log_WD8_Units)
R2(predict3, test$log_WD8_Units)
```

```{r}
#Linear Regression: Log-Log
d2mod1d <- lm(log_WD8_Units ~ log_WD8_Price + log_WD12_Price + log_SP10_Price + + Week, data = train)
summary(d2mod1d)
residualPlot(d2mod1d)
```


```{r}
#Predict Model1d and evalaute the metrics
predict4 <- predict(d2mod1d, test)
vif(d2mod1d)
RMSE(predict4, test$log_WD8_Units)
MAE(predict4, test$log_WD8_Units)
R2(predict4, test$log_WD8_Units)
```

```{r}
print("Log-log model gives better accuracy. So lets determine elasticity based on this model")
```


```{r}
#Estimating price elasticity for WD008
e_WD8a <- (-2.514 * (mean(finaldata2$log_WD8_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD8a,2)
print("A 10% increase in price for WD008 will result in 4.7% decrease in their demand")

#Estimating cross price elasticity for WD008
#Positive sign in the coefficent indicates that WD012 is a substitute for WD008
e_WD8b <- (0.785 * (mean(finaldata2$log_WD12_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD8b,2)
print("A 10% increase in price for WD012 will result in 1.6% increase in the demand for WD008")

#Negative sign in the coefficent indicates that SPC10 is a complement for WD008
e_WD8c <- (-0.386 * (mean(finaldata2$log_SP10_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD8c,2)
print("A 10% increase in price for SPC10 will result in 0.8% decrease in the demand for WD008")


##The demand for WD008 is not impacted by price change in SPC11
e1 <- c(round(e_WD8a,2), round(e_WD8b,2), round(e_WD8c,2) , NA)
e1
```


```{r}
#WD012 product
#Linear Regression: Linear-Linear
d2mod2a <- lm(WD12_Units ~ WD8_Units + WD12_Price + SP10_Units + SP10_Price + SP11_Price, data = train)
summary(d2mod2a)
residualPlot(d2mod2a)
```

```{r}
#Predict Model2a and evalaute the metrics
predict5 <- predict(d2mod2a, test)
vif(d2mod2a)
RMSE(predict5, test$WD12_Units)
MAE(predict5, test$WD12_Units)
R2(predict5, test$WD12_Units)
```

```{r}
#Linear Regression: Linear-Log
d2mod2b <- lm(WD12_Units ~ log_WD8_Units + log_WD12_Price + log_SP10_Units + log_SP10_Price + log_SP11_Price, data = train)
summary(d2mod2b)
residualPlot(d2mod2b)
```

```{r}
#Predict Model2b and evalaute the metrics
predict6 <- predict(d2mod2b, test)
vif(d2mod2b)
RMSE(predict6, test$WD12_Units)
MAE(predict6, test$WD12_Units)
R2(predict6, test$WD12_Units)
```

```{r}
#Linear Regression: Log-Linear
d2mod2c <- lm(log_WD12_Units ~ + WD8_Units + WD12_Price + SP10_Units + SP10_Price + SP11_Price, data = train)
summary(d2mod2c)
residualPlot(d2mod2c)
```

```{r}
#Predict Model2c and evalaute the metrics
predict7 <- predict(d2mod2c, test)
vif(d2mod2c)
RMSE(predict7, test$log_WD12_Units)
MAE(predict7, test$log_WD12_Units)
R2(predict7, test$log_WD12_Units)
```

```{r}
#Linear Regression: Log-Log
d2mod2d <- lm(log_WD12_Units ~ log_WD8_Price + log_WD12_Price + log_SP10_Units + log_SP10_Price + log_SP11_Price, data = train)
summary(d2mod2d)
residualPlot(d2mod2d)
```

```{r}
#Predict Model2d and evalaute the metrics
predict8 <- predict(d2mod2d, test)
vif(d2mod2d)
RMSE(predict8, test$log_WD12_Units)
MAE(predict8, test$log_WD12_Units)
R2(predict8, test$log_WD12_Units)
```

```{r}
#Estimating price elasticity for WD012
e_WD12b <- (-1.956 * (mean(finaldata2$log_WD12_Price)) / mean(finaldata2$log_WD12_Units))
round(e_WD12b,2)
print("A 10% increase in price for WD012 will result in 4% decrease in their demand")

#Estimating cross price elasticity for WD012
e_WD12a <- (0.749 * (mean(finaldata2$log_WD8_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD12a,2)
print("A 10% increase in price for WD008 will result in 1.4% increase in the demand for WD012")

e_WD12c <- (-0.955 * (mean(finaldata2$log_SP10_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD12c,2)
print("A 10% increase in price for SPC10 will result in 2% decrease in the demand for WD012")

e_WD12d <- (1.710 * (mean(finaldata2$log_SP11_Price) / mean(finaldata2$log_WD8_Units)))
round(e_WD12d,2)
print("A 10% increase in price for SPC11 will result in 3.5% increase in the demand for WD012")

e2 <- c( round(e_WD12a,2), round(e_WD12b,2), round(e_WD12c,2), round(e_WD12d,2))
e2
```


```{r}
#SPC10
#Linear Regression: Log-Log
d2mod3a <- lm(log_SP10_Units ~ log_SP10_Price + log_SP11_Units + log_SP11_Price + Week, data = train)
summary(d2mod3a)
residualPlot(d2mod3a)
```

```{r}
#Predict Model3a and evalaute the metrics
predict9 <- predict(d2mod3a, test)
vif(d2mod3a)
RMSE(predict9, test$log_SP10_Units)
MAE(predict9, test$log_SP10_Units)
R2(predict9, test$log_SP10_Units)
```


```{r}
#Estimating price elasticity for SPC10
e_SP10c <- (0.807 * (mean(finaldata2$log_SP10_Price)) / mean(finaldata2$log_SP10_Units))
round(e_SP10c,2)
print("A 10% increase in price for SPC10 will result in 2% increase in their demand")

#Estimating cross price elasticity for SPC10
e_SP10d <- (-0.965 * (mean(finaldata2$log_SP11_Price) / mean(finaldata2$log_SP10_Units)))
round(e_SP10d,2)
print("A 10% increase in price for SPC11 will result in 2.4% decrease in the demand for SPC10")

e3 <- c( NA, NA, round(e_SP10c,2), round(e_SP10d,2))
e3
```


```{r}
#SPC11
#Linear Regression: Log-Log
d2mod4a <- lm(log_SP11_Units ~ log_WD8_Units + log_WD12_Price + log_SP10_Units + log_SP10_Price + Week, data = train)
summary(d2mod4a)
residualPlot(d2mod4a)
```

```{r}
#Predict Model and evalaute the metrics
predict10 <- predict(d2mod4a, test)
vif(d2mod4a)
RMSE(predict10, test$log_SP11_Units)
MAE(predict10, test$log_SP11_Units)
R2(predict10, test$log_SP11_Units)
```


```{r}
#Estimating cross price elasticity for SPC11
e_SP11b <- (1.027* (mean(finaldata2$log_WD12_Price) / mean(finaldata2$log_SP11_Units)))
round(e_SP11b,2)
print("A 10% increase in price for WD012 will result in 2.3% increase in demand for SPC11")

e_SP11c <- (-0.846 * (mean(finaldata2$log_SP10_Price) / mean(finaldata2$log_SP11_Units)))
round(e_SP11c,2)
print("A 10% increase in price for SPC10 will result in 2% decrease in the demand for SPC11")

#SPC11 is not impacted by the change in its own price
e4 <- c( NA, round(e_SP11b,2), round(e_SP11c,2), NA)
e4
```


```{r}
e_Cust2 <- data.frame(e1,e2,e3,e4)

setnames(e_Cust2, old = c("e1","e2","e3", "e4"), new = c("WD008", "WD012", "SPC10", "SPC11"))
rownames(e_Cust2) <- c("WD008", "WD012", "SPC10", "SPC11")
e_Cust2

#The diagonals in the matrix represent the price elasticity. The elements in the off-diagonal represent the cross-price elasticity

#All the products are inelastic in nature as their absolute value of elasticity is between 0 and 1
```

























































